Move logs of vufind-reindex.sh to /var/log

diff --git a/packages/DEBIAN/postinst b/packages/DEBIAN/postinst
--- a/packages/DEBIAN/postinst
+++ b/packages/DEBIAN/postinst
@@ -36,7 +36,7 @@ ln -s $VUFIND_LOCAL_DIR/httpd-vufind.conf $APACHE_CONF_DIR/vufind.conf
 patch import/log4j.properties < local/import/log4j.properties.diff
 
 # Install Cronjob
-echo "15 4 * * * root . /etc/profile.d/vufind.sh; chronic bash -o pipefail -c '/usr/local/vufind/vufind-reindex.sh |& tee -a /usr/local/vufind/vufind-reindex.sh.log'" > /etc/cron.d/vufind-reindex
+echo "15 4 * * * root . /etc/profile.d/vufind.sh; chronic bash -o pipefail -c '/usr/local/vufind/vufind-reindex.sh |& tee -a /var/log/vufind-reindex.log'" > /etc/cron.d/vufind-reindex
 chown root:root /etc/cron.d/vufind-reindex
 chmod u=rw,go=r /etc/cron.d/vufind-reindex
 systemctl restart cron
